---
- hosts: localhost
  gather_facts: no

  tasks:
    - name: list tmp dir
      shell: ls -l /tmp >> /tmp/listatmp.txt

    - name: Get stats of the FS object
      ansible.builtin.stat:
        path: /tmp/listatmp.txt
      register: sym

