---
plugin: aws_ec2

regions:
  - us-east-1

filters:
  instance-state-name : running
  tag:Name: WebClusterTF

keyed_groups:
  - key: tags
    prefix: cluster_dir

compose:
  ansible_host: public_ip_address
